name: My Panda CI
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: My Build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.17.0
      - name: check go version
        run: |
          go version
      - name: run tests for go file
        run: go test

      - name: checkout private repo remotely
        uses: actions/checkout@v4
        with:
          repository: daryloye/CICDTest
          path: hiddenFolder
          token: ${{ secrets.DARYL}}

      - name: List out hidden things
        run: |
          ls
          cd hiddenFolder
          ls
