name: My Panda CI
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: My Build
    steps:
#      - name: Check out code
#        uses: actions/checkout@v4
#      - name: setup go
#        uses: actions/setup-go@v5.2.0
#        with:
#          go-version: 1.17.0
#      - name: check go version
#        run: |
#          go version
#      - name: run tests for go file
#        run: go test

      - name: checkout private repo remotely
        uses: actions/checkout@v4
        with:
          repository: daryloye/CICDTest
          path: hiddenFolder
          token: ${{ secrets.DARYL}}

      - name: List out hidden things
        run: |
          ls
          cd hiddenFolder
          ls
      - name: write to README
        run: |
          echo "hello Daryl, PJ here" > README.md

      - name: read updated README on github cloud
        run: |
          cat README.md

      - name: discord
        uses: discord-actions/message@v2
        with: 
          webhookUrl: https://discordapp.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
          #token: ${{ secrets.DISCORD}}
    # A message to send to Discord
          message: This is very cool!
    # A username for the message
          username: pjteh
      
    
